//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public string MENU_ID { get; set; }
        public string MENU_NAME { get; set; }
        public string ROLE_ID { get; set; }
        public string ACTION { get; set; }
        public string CONTROLLER { get; set; }
    }
}
