//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOURCE
    {
        public string SOURCE_ID { get; set; }
        public string SOURCE_NAME { get; set; }
    }
}
