//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDUCATION
    {
        public int EDUCATION_ID { get; set; }
        public string EDUCATION_NAME { get; set; }
        public string MAJOR { get; set; }
        public string DEGREE { get; set; }
        public Nullable<float> GPA { get; set; }
        public Nullable<System.DateTime> TAHUN_MASUK { get; set; }
        public Nullable<System.DateTime> TAHUN_LULUS { get; set; }
        public string CANDIDATE_ID { get; set; }
    }
}
