//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPERIENCE
    {
        public int EXPERIENCE_ID { get; set; }
        public string EXPERIENCE_NAME { get; set; }
        public string INDUSTRI { get; set; }
        public string POSISI { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string JOB_DESC { get; set; }
        public string SKILL { get; set; }
        public Nullable<int> SALARY { get; set; }
        public string PROJECT { get; set; }
        public string BENEFIT { get; set; }
        public string CANDIDATE_ID { get; set; }
    }
}
