//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SELECTION_HISTORY
    {
        public int HISTORY_ID { get; set; }
        public Nullable<int> PIC_ID { get; set; }
        public string CANDIDATE_ID { get; set; }
        public Nullable<System.DateTime> HISTORY_TIME { get; set; }
        public string STATE_ID { get; set; }
    
        public virtual CANDIDATE CANDIDATE { get; set; }
        public virtual USER USER { get; set; }
    }
}
